server:
  port: 9000

eureka:
  instance:
    hostname: 39.105.82.150
  client:
  #声明自己是个服务端
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# 名称
spring:
  application:
    name: eureka-server
# 自我保护模式禁止关闭，默认是开启状态true
#  server:
#    enable-self-preservation: false
